### PR TITLE
make phenotypes optional

### PR DESCRIPTION
**Pull request by harmsm**
I propose that we make the `phenotypes` argument optional in the `GenotypePhenotypeMap` constructor.  

A `GenotypePhenotypeMap` object is a very handy way to treat connectivity, mutations, and interface with the `epistasis` package--even without phenotypes.  I have run into just such a use case.  I am currently just making up phenotypes and sticking them in to the constructor.  I think it makes more sense for `gpmap` to create dummy phenotypes itself if none are specified.  I have implemented this change, having the library set all phenotypes to `1.0` if no phenotypes are given.  

Happy to discuss if there is some reason this change is undesirable.

### CODE REVIEW

**Comment by Zsailer** [comment]
This makes sense to me. Do you think we should make them `NaN` instead of an actual value?

**Comment by harmsm** [comment]
I think we should go with -1 and define the convention as -1 means no index.  A float index/NaN was just too weird as a user to have it as a workable solution.  -1 would signal something different is happening if all other values are positive.  It’s a compromise, but maybe a sane one?

**Comment by Zsailer** [comment]
`phenotype = -1` has meaning though. How do you distinguish that from phenotypes that acutally equal -1?

The **float** index/NaN stuff is fixed now. Pandas can now take `NaN`s in integer columns; I updated that in my GPMap PR. I had to explicitly set the column's dtype to `"Int64"`. (This was a common problem in Pandas that they finally fixed in the latest Pandas/Numpy). I'm not hard-set on this being the solution, but I'm not convined -1 is better...

**Comment by harmsm** [comment]
A NaN int makes sense.  I was thinking of the -1 as an index, not
phenotype.  But maybe I was thinking about it wrong.  The int solution
above solves the issue already, so that sounds good to me.

**Comment by harmsm** [comment]
Okay, just realized I completely spaced out on which PR I was looking at.  Yes, the NaN thing makes sense to me to avoid real -1 phenotypes.  Will implement.

**Pull request merged**
